import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist, Ubuntu } from "next/font/google";
import localFont from "next/font/local";

import { TRPCReactProvider } from "~/trpc/react";
import { HydrateClient } from "~/trpc/server";
import { joinClasses } from "~/libs/joinClasses";
import { AuthContext } from "./_components/ctx/authContext";
import { AuthProvider } from "./_components/ctx/authProvider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
});

const ubuntu = Ubuntu({
  weight: "700",
  variable: "--font-ubuntu",
});

const satoshi = localFont({
  src: "./fonts/Satoshi-Variable.woff2",
  variable: "--font-satoshi",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={joinClasses(
          geist.className,
          ubuntu.variable,
          satoshi.variable,
        )}
      >
        <TRPCReactProvider>
          <AuthProvider>
            <HydrateClient>{children}</HydrateClient>
          </AuthProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
